name: Update URLs in events
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         ref: dev
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "stage.cms.nwea.io"
          replace: "d1ushxurfijnsi.cloudfront.net"
          include: "events/*.html"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
