name: Events find/replace

on:
  push:
    paths:
      - 'events/*.html'

  workflow_dispatch:

jobs:
  build_events:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
         ref: dev

      # Setup 
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      # Runs a set of commands using the runners shell
      - name: Find and replace paths in events
        run: |
          git grep -l 'stage\.cms\.nwea\.io' | xargs sed -i 's/stage\.cms\.nwea\.io/nd1ushxurfijnsi\.cloudfront\.net/g'
          git add .
          git commit -m "Updated events paths"
