name: Update URLs in events
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "stage.cms.nwea.io"
          replace: "d1ushxurfijnsi.cloudfront.net"
          include: "events/**"
          regex: false
